columns = ['Bar', 'Disk', 'Ring', 'Core', 'Multiple', 'Compactness', 'AGN',
           'Pseudobulge', 'BCG', 'cD', 'M_BH', 'M_BH_std_sym', 'M*_sph', 'M*_gal', 'log_B/T',
           'log_sigma0', 'log_R_e_sph_maj','log_R_e_sph_eq_kpc', 'log_n_sph_maj', 'log_n_sph_eq', 'log(I_e,sph,maj/M_Sun/pc^2)',
           'log(I_e,sph,eq/M_Sun/pc^2)', 'Concentration_Index',
           'avg_Rho_1kpc_Exact_All', 'r1_density_approx', 'log10(R10_kpc)',
           'logRho_R10_approx', 'log_rho10_Exact', 'log10(R90_kpc)',
           'logRho_R90_approx', 'log_rho_90_Exact_all', 'Rho_re_spatial',
           'SR_pc_All', 'Rho_SR_pc_All', 'CR_def1_approx_new',
           'Rho_cr_def1_approx_new', 'CR_def2_approx_new',
           'Rho_CR_def2_approx_new', 'Sr(pc)_2_using_Falserm_drho',
           'Log_Approx_Avg_density_10pc', 'log_Rho_e_Exact_new',
           'logRho_e_approx_New', 'logRho_soi_approx_new',
           'log_Rho_soi_exact_new', 'Avg_Rho_Re_Exact_all',
           'Avg_Rho_soi_exact_all', 'Avg_Rho_re_Exact_all', 'Rho_re_Exact_all',
           'Rho_r_soi_2BH_approx', 'Log_Avg_Rho_10kpc_approx',
           'Log_Avg_Rho_10kpc_exact_final', 'Log_Avg_Rho_100pc_approx',
           'Log_Avg_Rho_5kpc_approx', 'Log_Avg_rho_5kpc_exact_all', 'ube', 'bve',
           'dc', 'bvtc', 'bri25', 'mabs', 'blum', 'logblum', 'logSigma0sph',
           'LogSigma0', 'R10', 'logR10', 'logR10phi', 'Rh', 'logRh', 'logRhphi',
           'logHalo']

low_scatter_para=['ETG','T-type','Bar', 'Disk', 'Ring', 'Core', 'Multiple', 'Compactness', 'AGN',
       'Pseudobulge', 'BCG', 'cD','M*_sph', 'M*_gal', 'log_B/T',
       'log_sigma0', 'log_R_e_sph_maj','log_R_e_sph_eq_kpc', 'log_n_sph_maj', 'log_n_sph_eq', 'log(I_e,sph,maj/M_Sun/pc^2)',
       'log(I_e,sph,eq/M_Sun/pc^2)', 'Concentration_Index',
       'avg_Rho_1kpc_Exact_All', 'r1_density_approx', 'log10(R10_kpc)',
       'logRho_R10_approx', 'log_rho10_Exact', 'log10(R90_kpc)',
       'logRho_R90_approx', 'log_rho_90_Exact_all', 'Rho_re_spatial',
       'SR_pc_All', 'Rho_SR_pc_All', 'CR_def1_approx_new',
       'Rho_cr_def1_approx_new', 'CR_def2_approx_new',
       'Rho_CR_def2_approx_new', 'Sr(pc)_2_using_Falserm_drho',
       'Log_Approx_Avg_density_10pc', 'log_Rho_e_Exact_new',
       'logRho_e_approx_New', 'logRho_soi_approx_new',
       'log_Rho_soi_exact_new', 'Avg_Rho_Re_Exact_all',
       'Avg_Rho_soi_exact_all', 'Avg_Rho_re_Exact_all', 'Rho_re_Exact_all',
       'Rho_r_soi_2BH_approx', 'Log_Avg_Rho_10kpc_approx',
       'Log_Avg_Rho_10kpc_exact_final', 'Log_Avg_Rho_100pc_approx',
       'Log_Avg_Rho_5kpc_approx', 'Log_Avg_rho_5kpc_exact_all', 'ube', 'bve',
       'dc', 'bvtc', 'bri25', 'mabs', 'blum', 'logblum', 'logSigma0sph',
       'LogSigma0', 'R10', 'logR10', 'logR10phi', 'Rh', 'logRh', 'logRhphi',
       'logHalo','B-V','V-[3.6]','GJC23W1-W2','GJC23W2-W3','GJC23log(M*,gal/M_sun)',
       'GJC23log(SFR)','GJC23log(sSFR)','<Sigma>_e','M_BH']

easy_obs_para=['LogSigma0','Concentration_Index','logSigma0sph','log_sigma0',
               'dc','logRhphi','M*_sph','ube','bri25','bve','bvtc','logR10phi',
               'M*_gal','log_B/T','logRh','log_n_sph_eq','blum','log_R_e_sph_maj',
               'logblum','log_n_sph_maj','logR10','Pseudobulge','AGN','Multiple',
               'Ring','BCG','Disk','cD','Bar','Core','Compactness','ETG','T-type',
               'M_BH','log10(R10_kpc)','log10(R90_kpc)','B-V','V-[3.6]','GJC23W1-W2',
               'GJC23W2-W3','GJC23log(M*,gal/M_sun)','M_BH']